<?php

namespace Poncho\AdminBundle\Maker;

use Poncho\AdminBundle\Maker\Utils\MakeHelper;
use Symfony\Bundle\MakerBundle\ConsoleStyle;
use Symfony\Bundle\MakerBundle\DependencyBuilder;
use Symfony\Bundle\MakerBundle\Generator;
use Symfony\Bundle\MakerBundle\InputConfiguration;
use Symfony\Bundle\MakerBundle\Maker\AbstractMaker;
use Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;

class MakeAdminSecurity extends AbstractMaker
{
    private const NAME = 'make:admin:security';
    private const DESCRIPTION = 'Configure security for admin';

    public function __construct(private readonly MakeHelper $helper)
    {
    }

    public static function getCommandName(): string
    {
        return self::NAME;
    }

    public static function getCommandDescription(): string
    {
        return self::DESCRIPTION;
    }

    public function configureCommand(Command $command, InputConfiguration $inputConfig): void
    {
    }

    public function configureDependencies(DependencyBuilder $dependencies): void
    {
    }

    public function interact(InputInterface $input, ConsoleStyle $io, Command $command): void
    {
    }

    public function generate(InputInterface $input, ConsoleStyle $io, Generator $generator): void
    {
        $entityClass = $this->helper->askEntityClass($io, 'AdminUser');

        $entity = $generator->createClassNameDetails($entityClass, 'Entity\\');
        $repository = $generator->createClassNameDetails($entityClass, 'Repository\\', 'Repository');

        $vars = [
            'entity' => $entity,
            'repository' => $repository
        ];

        $generator->generateClass(
            $entity->getFullName(),
            $this->helper->template('AdminUser.tpl.php'),
            $vars
        );
        $generator->generateClass(
            $repository->getFullName(),
            $this->helper->template('EntityRepository.tpl.php'),
            $vars
        );

        $this->createRouteConfig($generator);
        $this->createSecurityConfig($generator, $entity->getFullName());
        $this->updateFirewallAndAccessControl($io, $generator, $entity->getFullName());

        $generator->writeChanges();
        $this->successMessage($io);
    }

    /**
     * Writes a new, bundle-owned file rather than editing config/routes.yaml: it is
     * auto-imported the same way (Symfony's MicroKernelTrait globs config/routes/*.yaml
     * unconditionally), and never risks touching anything the application already has there.
     */
    private function createRouteConfig(Generator $generator): void
    {
        $generator->dumpFile('config/routes/poncho_admin_security.yaml', <<<YAML
            # Generated by make:admin:security. Safe to regenerate by re-running the command;
            # if you need to customize these imports, copy them into your own routes file instead
            # of editing this one — it may be overwritten.
            poncho_admin_profile_:
                resource: '@PonchoAdminBundle/config/routes/profile.php'
                prefix: /admin

            poncho_admin_user_:
                resource: '@PonchoAdminBundle/config/routes/user.php'
                prefix: /admin

            poncho_admin_security_:
                resource: '@PonchoAdminBundle/config/routes/security.php'
                prefix: /admin

            YAML);
    }

    /**
     * Writes a new, bundle-owned file rather than editing config/packages/poncho_admin.yaml and
     * config/packages/security.yaml: Symfony merges a "poncho_admin" tree, a "providers" tree and
     * a "password_hashers" tree across every file under config/packages/*.yaml, by key, with no
     * risk of clobbering anything already there.
     *
     * "firewalls" and "access_control" do NOT work this way and stay out of this file on purpose
     * — see updateFirewallAndAccessControl().
     */
    private function createSecurityConfig(Generator $generator, string $userClass): void
    {
        $generator->dumpFile('config/packages/poncho_admin_security.yaml', <<<YAML
            # Generated by make:admin:security. Safe to regenerate by re-running the command —
            # if you need to customize this, copy what you need into your own config instead of
            # editing this file, which may be overwritten.
            poncho_admin:
                user:
                    class: {$userClass}

            security:
                password_hashers:
                    {$userClass}: auto
                providers:
                    admin_entity_provider:
                        entity:
                            class: {$userClass}
                            property: email

            YAML);
    }

    /**
     * "firewalls" and "access_control" cannot be split across config files the way the rest of
     * this maker's config can: Symfony's SecurityBundle explicitly rejects a *new* firewall
     * defined in a second file ("You are not allowed to define new elements for path
     * security.firewalls […] define all elements for this path in one config file"), and rejects
     * "access_control" being set in more than one file at all ("cannot be overwritten […] define
     * all options for this path […] in one configuration section"). Both are enforced at
     * container-compile time, verified against a real kernel boot — not a style preference this
     * maker could route around.
     *
     * So this one edit has to land in the application's own config/packages/security.yaml, same
     * as before. What changes is that it is now a genuine merge: the existing "firewalls" map
     * keeps every firewall already there (a new "admin" key is just added alongside them), and
     * the existing "access_control" list keeps every rule already there — this maker's four rules
     * are prepended, not substituted for it. Previously this replaced the whole array, discarding
     * any pre-existing access_control rules.
     */
    private function updateFirewallAndAccessControl(ConsoleStyle $io, Generator $generator, string $userClass): void
    {
        $configPath = 'config/packages/security.yaml';

        if (!$this->helper->fileExists($configPath)) {
            $io->warning('The file "config/packages/security.yaml" does not exist. PHP & XML configuration formats are currently not supported. You have to configure security manually — see the documentation.');

            return;
        }

        $manipulator = new YamlSourceManipulator($this->helper->getFileContents($configPath));
        $data = $manipulator->getData();

        $data['security']['firewalls']['admin'] = [
            'pattern' => '^/admin',
            'user_checker' => 'Poncho\AdminBundle\Security\UserChecker',
            'entry_point' => 'Poncho\AdminBundle\Security\AuthenticationEntryPoint',
            'provider' => 'admin_entity_provider',
            'lazy' => true,
            'form_login' => [
                'login_path' => 'poncho_admin_login',
                'check_path' => 'poncho_admin_login',
                'default_target_path' => 'app_admin_home_index',
                'enable_csrf' => true
            ],
            'logout' => [
                'path' => 'poncho_admin_logout',
                'target' => 'poncho_admin_login'
            ]
        ];

        $ourRules = [
            ['path' => '^/admin/login$', 'roles' => 'PUBLIC_ACCESS'],
            ['path' => '^/admin/password-reset', 'roles' => 'PUBLIC_ACCESS'],
            // The profile page changes the password and e-mail without asking for the current
            // password, so it requires a fresh login rather than only a remembered session.
            ['path' => '^/admin/profile', 'roles' => 'IS_AUTHENTICATED_FULLY'],
            ['path' => '^/admin', 'roles' => 'ROLE_ADMIN'],
        ];
        // YamlSourceManipulator reliably adds a brand new key (like "firewalls.admin" above),
        // but cannot reliably *append* to a list that already has at least one entry — verified:
        // it corrupts the YAML regardless of whether the existing entries are flow- or
        // block-style. So when access_control already has entries, leave the key out of $data
        // entirely (nothing for the manipulator to get wrong) and splice our rules in as text,
        // immediately after the "access_control:" line, once the rest of the diff is applied.
        $hasExistingRules = !empty($data['security']['access_control']);
        if (!$hasExistingRules) {
            $data['security']['access_control'] = $ourRules;
        }

        $manipulator->setData($data);
        $contents = $manipulator->getContents();

        if ($hasExistingRules) {
            $contents = $this->prependAccessControlRules($contents, $ourRules);
        }

        $generator->dumpFile($configPath, $contents);
    }

    /**
     * Inserts $rules as new block-style list items directly under the first
     * "access_control:" line found, ahead of whatever is already there — see
     * updateFirewallAndAccessControl() for why this works at the text level when
     * YamlSourceManipulator's own data diffing does not.
     */
    private function prependAccessControlRules(string $yaml, array $rules): string
    {
        $lines = explode("\n", $yaml);

        foreach ($lines as $i => $line) {
            if (!preg_match('/^(\s*)access_control:\s*$/', $line, $matches)) {
                continue;
            }

            $itemIndent = $matches[1] . '    ';
            $fieldIndent = $itemIndent . '  ';

            $newLines = [];
            foreach ($rules as $rule) {
                $newLines[] = $itemIndent . '- path: ' . $rule['path'];
                $newLines[] = $fieldIndent . 'roles: ' . $rule['roles'];
            }

            array_splice($lines, $i + 1, 0, $newLines);

            return implode("\n", $lines);
        }

        // "access_control:" not found as a lone key line — leave the file untouched rather
        // than risk corrupting it; this should not happen given $hasExistingRules was true.
        return $yaml;
    }

    private function successMessage(ConsoleStyle $io): void
    {
        $this->writeSuccessMessage($io);

        $io->text([
            'Next:',
            '  1) Update your database schema with command <fg=yellow>"php bin/console doctrine:schema:update --force"</>.',
            '  2) Generate an admin user with command <fg=yellow>"php bin/console poncho_admin:create:user"</>.',
            '  3) Add section for route <fg=yellow>"poncho_admin_user_index"</> on your Admin menu.',
        ]);

        $io->newLine();
        $io->writeln('Open your browser, go to "/admin" to login');
        $io->writeln('Once logged, go to "/admin/user" to manage user');
        $io->newLine();
        $io->writeln('Read more about it on <href=https://beaumu.github.io/poncho-admin-bundle/#/getting-started/configure_security>Documentation</>');
        $io->newLine();
    }
}
