<?php

namespace Poncho\AdminBundle\Maker;

use Poncho\AdminBundle\Maker\Utils\MakeHelper;
use Symfony\Bundle\MakerBundle\ConsoleStyle;
use Symfony\Bundle\MakerBundle\DependencyBuilder;
use Symfony\Bundle\MakerBundle\Generator;
use Symfony\Bundle\MakerBundle\InputConfiguration;
use Symfony\Bundle\MakerBundle\Maker\AbstractMaker;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;

class MakeNotification extends AbstractMaker
{
    private const NAME = 'make:admin:notification';
    private const DESCRIPTION = 'Generate an admin notification provider';

    public function __construct(private readonly MakeHelper $helper)
    {
    }

    public static function getCommandName(): string
    {
        return self::NAME;
    }

    public static function getCommandDescription(): string
    {
        return self::DESCRIPTION;
    }

    public function configureCommand(Command $command, InputConfiguration $inputConfig): void
    {
    }

    public function configureDependencies(DependencyBuilder $dependencies): void
    {
    }

    public function generate(InputInterface $input, ConsoleStyle $io, Generator $generator): void
    {
        $entity = $generator->createClassNameDetails('AdminNotification', 'Entity\\');
        $repository = $generator->createClassNameDetails($entity->getShortName(), 'Repository\\', 'Repository');
        $provider = $generator->createClassNameDetails('AdminNotification', 'Notification\\', 'Provider');

        $vars = [
            'entity' => $entity,
            'repository' => $repository,
            'provider' => $provider
        ];

        $generator->generateClass(
            $entity->getFullName(),
            $this->helper->template('notification/NotificationEntity.tpl.php'),
            $vars
        );
        $generator->generateClass(
            $repository->getFullName(),
            $this->helper->template('EntityRepository.tpl.php'),
            $vars
        );
        $generator->generateClass(
            $provider->getFullName(),
            $this->helper->template('notification/NotificationProvider.tpl.php'),
            $vars
        );

        $this->createRouteConfig($generator);
        $this->createNotificationConfig($generator, $provider->getFullName());

        $generator->writeChanges();
        $this->successMessage($io, $provider->getFullName());
    }

    /**
     * Writes a new, bundle-owned file rather than editing config/routes.yaml — see
     * MakeAdminSecurity::createRouteConfig() for why.
     */
    private function createRouteConfig(Generator $generator): void
    {
        $generator->dumpFile('config/routes/poncho_admin_notification.yaml', <<<YAML
            # Generated by make:admin:notification. Safe to regenerate by re-running the command;
            # if you need to customize this import, copy it into your own routes file instead of
            # editing this one — it may be overwritten.
            poncho_admin_notification_:
                resource: '@PonchoAdminBundle/config/routes/notification.php'
                prefix: /admin

            YAML);
    }

    /**
     * Writes a new, bundle-owned file rather than editing
     * config/packages/poncho_admin.yaml — see
     * MakeAdminSecurity::createSecurityConfig() for why this is safe: Symfony merges
     * the "poncho_admin" tree across every file under config/packages/*.yaml.
     */
    private function createNotificationConfig(Generator $generator, string $providerClass): void
    {
        $generator->dumpFile('config/packages/poncho_admin_notification.yaml', <<<YAML
            # Generated by make:admin:notification. Safe to regenerate by re-running the
            # command — if you need to customize this, copy it into your own config instead of
            # editing this file, which may be overwritten.
            poncho_admin:
                notification:
                    provider: {$providerClass}
                    poll_interval: 10

            YAML);
    }

    private function successMessage(ConsoleStyle $io, string $providerClass): void
    {
        $this->writeSuccessMessage($io);

        $io->text([
            'Next:',
            '  1) Update your database schema with command <fg=yellow>"php bin/console doctrine:schema:update --force"</>.',
            \sprintf('  2) Customize how notification are fetched on class <fg=yellow>%s</>".', $providerClass),
            '  3) Create and send new notification.',
        ]);

        $io->newLine();
        $io->writeln('Read more about it on <href=https://beaumu.github.io/poncho-admin-bundle/#/component/notification>Documentation</>');
        $io->newLine();
    }
}
