<?php

namespace Poncho\AdminBundle\Maker;

use Poncho\AdminBundle\Maker\Utils\MakeHelper;
use Symfony\Bundle\MakerBundle\ConsoleStyle;
use Symfony\Bundle\MakerBundle\DependencyBuilder;
use Symfony\Bundle\MakerBundle\Generator;
use Symfony\Bundle\MakerBundle\InputConfiguration;
use Symfony\Bundle\MakerBundle\Maker\AbstractMaker;
use Symfony\Bundle\MakerBundle\Str;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;

class MakeHome extends AbstractMaker
{
    private const NAME = 'make:admin:home';
    private const DESCRIPTION = 'Generate an admin home';

    public function __construct(private readonly MakeHelper $helper)
    {
    }

    public static function getCommandName(): string
    {
        return self::NAME;
    }

    public static function getCommandDescription(): string
    {
        return self::DESCRIPTION;
    }

    public function configureCommand(Command $command, InputConfiguration $inputConfig): void
    {
    }

    public function configureDependencies(DependencyBuilder $dependencies): void
    {
    }

    public function interact(InputInterface $input, ConsoleStyle $io, Command $command): void
    {
    }

    public function generate(InputInterface $input, ConsoleStyle $io, Generator $generator): void
    {
        $controllerClass = $this->helper->askControllerClass($io, 'Admin\\HomeController');

        $controller = $generator->createClassNameDetails($controllerClass, 'Controller\\', 'Controller');
        $menu = $generator->createClassNameDetails('AdminMenu', 'Menu\\', 'Menu');

        $vars = [
            'controller' => $controller,
            'route' => $this->helper->getRouteConfig($controller, '/admin'),
            'menu' => $menu,
            'template' => Str::asFilePath($controller->getRelativeNameWithoutSuffix()) . '/index.html.twig'
        ];

        $generator->generateClass(
            $controller->getFullName(),
            $this->helper->template('HomeController.tpl.php'),
            $vars
        );
        $generator->generateClass(
            $menu->getFullName(),
            $this->helper->template('Menu.tpl.php'),
            $vars
        );
        $generator->generateTemplate(
            $vars['template'],
            $this->helper->template('template_home.tpl.php'),
            $vars
        );
        $this->createMenuConfig($generator, $menu->getFullName());

        $generator->writeChanges();
        $this->successMessage($io);
    }

    /**
     * Writes a new, bundle-owned file rather than editing
     * config/packages/poncho_admin.yaml — see
     * MakeAdminSecurity::createSecurityConfig() for why this is safe: Symfony merges
     * the "poncho_admin" tree across every file under config/packages/*.yaml.
     */
    private function createMenuConfig(Generator $generator, string $menuClass): void
    {
        $generator->dumpFile('config/packages/poncho_admin_home.yaml', <<<YAML
            # Generated by make:admin:home. Safe to regenerate by re-running the command — if
            # you need to customize this, copy it into your own config instead of editing this
            # file, which may be overwritten.
            poncho_admin:
                app_name: Admin
                menu: {$menuClass}

            YAML);
    }

    private function successMessage(ConsoleStyle $io): void
    {
        $this->writeSuccessMessage($io);
        $io->newLine();
        $io->text('Open your browser, go to "/admin" and enjoy!');
        $io->newLine();
    }
}
